name: reflex
channels:
  - pytorch
  - defaults
dependencies:
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2019.11.27
  - cairo=1.14.12
  - certifi=2019.11.28
  - cffi=1.13.2
  - cycler=0.10.0
  - ffmpeg=4.0
  - fontconfig=2.13.0
  - freetype=2.9.1
  - gettext=0.19.8.1
  - glib=2.63.1
  - graphite2=1.3.13
  - harfbuzz=1.8.8
  - hdf5=1.10.2
  - icu=58.2
  - intel-openmp=2019.4
  - jasper=2.0.14
  - joblib=0.14.1
  - jpeg=9b
  - kiwisolver=1.1.0
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgfortran=3.0.1
  - libiconv=1.15
  - libopencv=3.4.2
  - libopus=1.3
  - libpng=1.6.37
  - libtiff=4.1.0
  - libvpx=1.7.0
  - libxml2=2.9.9
  - llvm-openmp=4.0.1
  - matplotlib=3.1.1
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - ncurses=6.1
  - ninja=1.9.0
  - numpy=1.17.4
  - numpy-base=1.17.4
  - olefile=0.46
  - opencv=3.4.2
  - openssl=1.1.1d
  - pandas=0.25.3
  - pcre=8.43
  - pillow=7.0.0
  - pip=19.3.1
  - pixman=0.38.0
  - py-opencv=3.4.2
  - pycparser=2.19
  - pyparsing=2.4.6
  - python=3.7.6
  - python-dateutil=2.8.1
  - pytorch=0.4.1
  - pytz=2019.3
  - readline=7.0
  - scikit-learn=0.22.1
  - scipy=1.3.1
  - setuptools=44.0.0
  - six=1.13.0
  - sqlite=3.30.1
  - tk=8.6.8
  - tornado=6.0.3
  - wheel=0.33.6
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7

