# Generated by Django 2.1.3 on 2018-11-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutputScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('loop_scattering', models.FloatField(default=0, max_length=10)),
                ('background_ring', models.FloatField(default=0, max_length=10)),
                ('strong_background', models.FloatField(default=0, max_length=10)),
                ('diffuse_scattering', models.FloatField(default=0, max_length=10)),
                ('artifact', models.FloatField(default=0, max_length=10)),
                ('ice_ring', models.FloatField(default=0, max_length=10)),
                ('non_uniform_detector', models.FloatField(default=0, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserAdding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
    ]
