# Generated by Django 2.1.1 on 2018-10-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                #('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                #('nameOfFile', models.CharField(max_length=130)),
                #('yourEmail', models.EmailField(blank=True, max_length=254)),
                #('linkToFile', models.CharField(blank=True, max_length=30)),
                #('bio', models.TextField(blank=True)),

                #nameOfFile = models.CharField(max_length=130)
                #yourEmail = models.EmailField(blank=True)
                #linkToFile = models.CharField(max_length=50, blank=False)

                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('job_title', models.CharField(blank=True, max_length=30)),
                ('bio', models.TextField(blank=True)),
            ],
        ),
    ]
