# Generated by Django 2.1.1 on 2018-11-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamineType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examine_type', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(default='static/getPhotos/None/no-img.jpg', upload_to='static/getPhotos')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfFile', models.CharField(max_length=130)),
                ('yourEmail', models.EmailField(max_length=254)),
                ('linkToFile', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserAdding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(default='static/getPhotos/None/no-img.jpg', upload_to='static/getPhotos')),
                ('examine_type', models.ForeignKey(on_delete='cascade', to='mainPage.ExamineType')),
            ],
        ),
    ]
