# Generated by Django 2.1.1 on 2018-11-06 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0001_initial'),
    ]

    operations = [
    ]
