# Generated by Django 2.1.1 on 2018-11-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0002_auto_20181119_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examinetype',
            name='examine_type',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='useradding',
            name='pic',
            field=models.ImageField(upload_to=''),
        ),
    ]
