# Generated by Django 2.1.1 on 2018-11-06 13:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0002_auto_20181106_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='nameOfFile',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='email',
            new_name='yourEmail',
        ),
        migrations.RemoveField(
            model_name='person',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='person',
            name='job_title',
        ),
        migrations.AddField(
            model_name='person',
            name='linkToFile',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
