# Generated by Django 2.1.1 on 2018-11-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0003_auto_20181106_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(default='static/getPhotos/None/no-img.jpg', upload_to='static/getPhotos')),
            ],
        ),
    ]
