# Generated by Django 2.1.1 on 2018-11-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0003_auto_20181120_1246'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AlterField(
            model_name='useradding',
            name='pic',
            field=models.ImageField(default='test_photos/noname.jpg', upload_to='test_photos/'),
        ),
    ]
