# Generated by Django 2.1.1 on 2018-11-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0004_auto_20181127_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradding',
            name='pic',
            field=models.ImageField(default='mainPage/test_photos/noname.jpg', upload_to='mainPage/test_photos/'),
        ),
    ]
